name: base
channels:
  - defaults
dependencies:
  - anaconda-anon-usage=0.7.4=pyhb46e38b_100
  - anaconda-auth=0.10.0=py313hca03da5_1
  - anaconda-cli-base=0.6.0=py313hca03da5_0
  - annotated-types=0.6.0=py313hca03da5_1
  - anyio=4.10.0=py313hca03da5_0
  - aom=3.12.1=ha237518_0
  - appnope=0.1.4=py313hca03da5_0
  - archspec=0.2.5=pyhd3eb1b0_0
  - argon2-cffi=25.1.0=py313hca03da5_0
  - argon2-cffi-bindings=25.1.0=py313h254cc4a_0
  - asttokens=3.0.0=py313hca03da5_0
  - async-lru=2.0.5=py313hca03da5_0
  - attrs=25.4.0=py313hca03da5_2
  - babel=2.17.0=py313hca03da5_0
  - beautifulsoup4=4.14.2=py313hca03da5_0
  - blas=1.0=openblas
  - bleach=6.3.0=py313hca03da5_0
  - boltons=25.0.0=py313hca03da5_0
  - bottleneck=1.4.2=py313h03d0aa3_1
  - brotlicffi=1.0.9.2=py313h50f4ffc_2
  - bzip2=1.0.8=h80987f9_6
  - c-ares=1.34.5=h2ca31fc_0
  - ca-certificates=2025.12.2=hca03da5_0
  - cairo=1.18.4=h191e429_0
  - certifi=2026.01.04=py313hca03da5_0
  - cffi=2.0.0=py313h73c2a22_1
  - charset-normalizer=3.4.4=py313hca03da5_0
  - click=8.1.8=py313hca03da5_0
  - comm=0.2.3=py313hca03da5_0
  - conda=25.11.1=py313hca03da5_0
  - conda-anaconda-telemetry=0.3.0=pyhd3eb1b0_1
  - conda-anaconda-tos=0.2.2=py313hca03da5_1
  - conda-content-trust=0.2.0=py313hca03da5_1
  - conda-libmamba-solver=25.4.0=pyhdf14ebd_1
  - conda-package-handling=2.4.0=py313hca03da5_1
  - conda-package-streaming=0.12.0=py313hca03da5_1
  - contourpy=1.3.3=py313h20e30b6_0
  - cpp-expected=1.1.0=h48ca7d4_0
  - cryptography=46.0.3=py313h81b0bee_0
  - cycler=0.12.1=py313hca03da5_0
  - dav1d=1.2.1=h80987f9_0
  - debugpy=1.8.16=py313h50f4ffc_1
  - decorator=5.2.1=py313hca03da5_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - distro=1.9.0=py313hca03da5_0
  - executing=2.2.1=py313hca03da5_0
  - expat=2.7.3=h982b769_0
  - fmt=11.2.0=h643473a_0
  - fontconfig=2.15.0=h29935d0_0
  - fonttools=4.61.0=py313haa24f5a_0
  - freetype=2.13.3=h47d26ad_0
  - fribidi=1.0.10=h1a28f6b_0
  - frozendict=2.4.6=py313haa24f5a_0
  - gettext=0.21.0=hbdbcc25_2
  - graphite2=1.3.14=hc377ac9_1
  - h11=0.16.0=py313hca03da5_1
  - harfbuzz=10.2.0=he637ebf_1
  - html5lib=1.1=pyhd3eb1b0_0
  - httpcore=1.0.9=py313hca03da5_0
  - httpx=0.28.1=py313hca03da5_1
  - icu=73.1=h313beb8_0
  - idna=3.11=py313hca03da5_0
  - ipykernel=6.31.0=py313h7eb115d_0
  - ipython=9.7.0=py313hca03da5_0
  - ipython_pygments_lexers=1.1.1=py313hca03da5_0
  - ipywidgets=8.1.7=py313hca03da5_0
  - jansson=2.14=h80987f9_1
  - jaraco.classes=3.4.0=py313hca03da5_0
  - jaraco.context=6.0.0=py313hca03da5_0
  - jaraco.functools=4.1.0=py313hca03da5_0
  - jedi=0.19.2=py313hca03da5_0
  - jinja2=3.1.6=py313hca03da5_0
  - joblib=1.5.3=py313hca03da5_0
  - jpeg=9f=h2f69dba_0
  - json5=0.12.1=py313hca03da5_0
  - jsonpatch=1.33=py313hca03da5_1
  - jsonpointer=3.0.0=py313hca03da5_0
  - jsonschema=4.25.1=py313hca03da5_0
  - jsonschema-specifications=2025.9.1=py313hca03da5_0
  - jupyter=1.1.1=py313hca03da5_0
  - jupyter-lsp=2.2.5=py313hca03da5_0
  - jupyter_client=8.6.3=py313hca03da5_1
  - jupyter_console=6.6.3=py313hca03da5_1
  - jupyter_core=5.9.1=py313hca03da5_0
  - jupyter_events=0.12.0=py313hca03da5_1
  - jupyter_server=2.17.0=py313hca03da5_0
  - jupyter_server_terminals=0.5.3=py313hca03da5_0
  - jupyterlab=4.5.0=py313hca03da5_0
  - jupyterlab_pygments=0.3.0=py313hca03da5_0
  - jupyterlab_server=2.28.0=py313hca03da5_0
  - jupyterlab_widgets=3.0.15=py313hca03da5_0
  - keyring=25.6.0=py313hca03da5_0
  - kiwisolver=1.4.9=py313haeee614_0
  - lcms2=2.17=h7418793_0
  - lerc=4.0.0=h313beb8_0
  - libarchive=3.8.2=ha845c4f_0
  - libavif=1.3.0=h839b4eb_0
  - libcurl=8.16.0=h01d3526_0
  - libcxx=20.1.8=hd7fd590_1
  - libdeflate=1.22=h80987f9_0
  - libev=4.33=h1a28f6b_1
  - libffi=3.4.4=hca03da5_1
  - libgfortran5=15.2.0=hb654fa1_1
  - libglib=2.84.4=h7a3292d_0
  - libiconv=1.16=h80987f9_3
  - libidn2=2.3.8=h9681e36_0
  - libmamba=2.3.2=he2fa6f2_0
  - libmambapy=2.3.2=py313he835dd0_0
  - libmpdec=4.0.0=h80987f9_0
  - libnghttp2=1.67.1=h8189af8_0
  - libopenblas=0.3.30=hf2bb037_2
  - libopenjpeg=2.5.4=haa24f5a_1
  - libpng=1.6.50=h5c318fc_0
  - libsodium=1.0.20=h897f8a9_0
  - libsolv=0.7.30=ha443353_2
  - libssh2=1.11.1=h3e2b118_0
  - libtiff=4.7.1=h367c460_0
  - libunistring=1.3=h1799b2a_0
  - libwebp-base=1.6.0=h92b2d59_0
  - libxml2=2.13.9=h528a072_0
  - libzlib=1.3.1=h5f15de7_0
  - llvm-openmp=20.1.8=he822017_0
  - lz4-c=1.9.4=h313beb8_1
  - markdown-it-py=4.0.0=py313hca03da5_0
  - markupsafe=3.0.2=py313h80987f9_0
  - matplotlib=3.10.7=py313hca03da5_0
  - matplotlib-base=3.10.7=py313haa222d5_0
  - matplotlib-inline=0.2.1=py313hca03da5_0
  - mdurl=0.1.2=py313hca03da5_0
  - menuinst=2.4.1=py313hca03da5_1
  - mistune=3.1.2=py313hca03da5_0
  - more-itertools=10.8.0=py313hca03da5_0
  - nbclient=0.10.2=py313hca03da5_0
  - nbconvert=7.16.6=py313hca03da5_0
  - nbconvert-core=7.16.6=py313hca03da5_0
  - nbconvert-pandoc=7.16.6=py313hca03da5_0
  - nbformat=5.10.4=py313hca03da5_0
  - ncurses=6.5=hee39554_0
  - nest-asyncio=1.6.0=py313hca03da5_0
  - nlohmann_json=3.11.2=h313beb8_0
  - notebook=7.5.0=py313hca03da5_0
  - notebook-shim=0.2.4=py313hca03da5_0
  - numexpr=2.14.1=py313h5fbe615_0
  - numpy=2.3.5=py313h4bb6f22_0
  - numpy-base=2.3.5=py313h23175f9_0
  - openssl=3.0.18=h9b4081a_0
  - packaging=25.0=py313hca03da5_1
  - pandas=2.3.3=py313h3f644e9_1
  - pandoc=3.8=hca03da5_0
  - pandocfilters=1.5.1=py313hca03da5_0
  - parso=0.8.5=py313hca03da5_0
  - pcre2=10.46=h1dacb4a_0
  - pexpect=4.9.0=py313hca03da5_1
  - pillow=12.0.0=py313he2d6fe4_1
  - pip=25.2=pyhc872135_1
  - pixman=0.46.4=h09dc60e_0
  - pkce=1.0.3=py313hca03da5_0
  - platformdirs=4.5.0=py313hca03da5_0
  - pluggy=1.5.0=py313hca03da5_0
  - prometheus_client=0.21.1=py313hca03da5_0
  - prompt-toolkit=3.0.52=py313hca03da5_1
  - prompt_toolkit=3.0.52=hd3eb1b0_1
  - psutil=7.0.0=py313haa24f5a_1
  - ptyprocess=0.7.0=pyhd3eb1b0_3
  - pure_eval=0.2.3=py313hca03da5_0
  - pybind11-abi=5=hd3eb1b0_0
  - pycosat=0.6.6=py313h80987f9_2
  - pycparser=2.23=py313hca03da5_0
  - pydantic=2.12.3=py313hca03da5_1
  - pydantic-core=2.41.4=py313h108b7f8_0
  - pydantic-settings=2.10.1=py313hca03da5_0
  - pygments=2.19.2=py313hca03da5_0
  - pyjwt=2.10.1=py313hca03da5_0
  - pyparsing=3.2.5=py313hca03da5_0
  - pysocks=1.7.1=py313hca03da5_1
  - python=3.13.9=hc7d8306_100_cp313
  - python-dateutil=2.9.0post0=py313hca03da5_2
  - python-dotenv=1.1.0=py313hca03da5_0
  - python-fastjsonschema=2.21.2=py313hca03da5_0
  - python-json-logger=4.0.0=py313hca03da5_0
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python.app=3=py313h80987f9_2
  - python_abi=3.13=1_cp313
  - pytz=2025.2=py313hca03da5_0
  - pyyaml=6.0.3=py313h091b9d3_0
  - pyzmq=27.1.0=py313h5a8c52c_1
  - qtconsole=5.7.0=py313hca03da5_0
  - qtpy=2.4.3=py313hca03da5_0
  - readchar=4.2.1=py313hca03da5_0
  - readline=8.3=h0b18652_0
  - referencing=0.37.0=py313hca03da5_0
  - reproc=14.2.4=h313beb8_2
  - reproc-cpp=14.2.4=h313beb8_2
  - requests=2.32.5=py313hca03da5_1
  - rfc3339-validator=0.1.4=py313hca03da5_0
  - rfc3986-validator=0.1.1=py313hca03da5_0
  - rich=14.2.0=py313hca03da5_0
  - rpds-py=0.28.0=py313h931abed_0
  - ruamel.yaml=0.18.16=py313h091b9d3_0
  - ruamel.yaml.clib=0.2.14=py313h091b9d3_0
  - scikit-learn=1.8.0=py313h003a250_0
  - scipy=1.16.3=py313h08a1045_0
  - seaborn=0.13.2=py313hca03da5_3
  - semver=3.0.4=py313hca03da5_0
  - send2trash=1.8.3=py313hca03da5_0
  - setuptools=80.9.0=py313hca03da5_0
  - shellingham=1.5.4=py313hca03da5_0
  - simdjson=3.10.1=h48ca7d4_0
  - six=1.17.0=py313hca03da5_0
  - sniffio=1.3.1=py313hca03da5_0
  - soupsieve=2.5=py313hca03da5_0
  - sqlite=3.51.0=hab6afd1_0
  - stack_data=0.6.3=py313hca03da5_0
  - terminado=0.18.1=py313hca03da5_0
  - threadpoolctl=3.5.0=py313h7eb115d_1
  - tinycss2=1.4.0=py313hca03da5_0
  - tk=8.6.15=hcd8a7d5_0
  - tomli=2.2.1=py313hca03da5_0
  - tornado=6.5.4=py313haa24f5a_0
  - tqdm=4.67.1=py313h7eb115d_1
  - traitlets=5.14.3=py313hca03da5_0
  - truststore=0.10.1=py313hca03da5_1
  - typer=0.17.4=py313hca03da5_0
  - typing-extensions=4.15.0=py313hca03da5_0
  - typing-inspection=0.4.2=py313hca03da5_0
  - typing_extensions=4.15.0=py313hca03da5_0
  - tzdata=2025b=h04d1e81_0
  - urllib3=2.5.0=py313hca03da5_0
  - wcwidth=0.2.14=py313hca03da5_0
  - webencodings=0.5.1=py313hca03da5_2
  - websocket-client=1.8.0=py313hca03da5_0
  - wheel=0.45.1=py313hca03da5_0
  - widgetsnbextension=4.0.14=py313hca03da5_0
  - xz=5.6.4=h80987f9_1
  - yaml=0.2.5=h1a28f6b_0
  - yaml-cpp=0.8.0=h313beb8_1
  - zeromq=4.3.5=h2c7f8f0_1
  - zlib=1.3.1=h5f15de7_0
  - zstandard=0.24.0=py313hbc14757_0
  - zstd=1.5.7=h817c040_0
prefix: /opt/miniconda3
